[theme]
base                       = "dark"
primaryColor               = "#40B391"
backgroundColor            = "#0F1A16"
secondaryBackgroundColor   = "#1A2B24"
textColor                  = "#E8F5EF"
font                       = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
